### ISSUE TITLE
Doesn't Run in MyBinder?

### ISSUE THREAD

**Issue by psychemedia** [nteract/dx#7]
Aside from the missing `pandas` dependency, which is easily rectified, the demo notebook doesn't display an explorable dataframe in MyBinder, it just displays a flat pandas df as normal. Any particular reason why it shouldn't work there?

**Comment by betatim** [comment]
I think that is related to #5. On mybinder.org (and repo2docker in general) you can also use the nteract frontend which does have DX support: https://mybinder.org/v2/gh/nteract/dx/master?urlpath=nteract%2Fedit%2Fdx-example.ipynb (still needs pandas installing)

**Comment by willingc** [comment]
Closed by #20
